import { LEGAL } from '../_content/constants';

export const metadata = { title: 'Terms of Service — drill' };

export default function TermsPage() {
  return (
    <article>
      <h1>Terms of Service</h1>

      <h2>The service</h2>
      <p>
        drill is an AI-assisted language-learning app for active production practice,
        operated by {LEGAL.controller} ({LEGAL.basedIn}). By using drill you agree to these terms.
      </p>

      <h2>Eligibility</h2>
      <p>You must be at least {LEGAL.minAge} years old to use drill.</p>

      <h2>Acceptable use</h2>
      <p>
        Use drill for your own language learning. Do not abuse, overload, or attempt to
        circumvent the Service&rsquo;s rate limits or security, and do not submit unlawful content.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Exercises, explanations, and evaluations are generated by AI and may contain errors.
        They are study aids, not professional, educational, or certified language assessment.
        Use your judgement.
      </p>

      <h2>No warranty</h2>
      <p>
        The Service is provided &ldquo;as is&rdquo; without warranties of any kind. To the
        fullest extent permitted by law, we are not liable for any indirect or consequential
        loss arising from your use of the Service.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these terms; the &ldquo;Last updated&rdquo; date below reflects the
        current version. Continued use after a change means you accept it.
      </p>

      <h2>Governing law</h2>
      <p>These terms are governed by the laws of {LEGAL.governingLaw}.</p>

      <h2>Contact</h2>
      <p>Questions? Email <a href={`mailto:${LEGAL.contactEmail}`}>{LEGAL.contactEmail}</a>.</p>
    </article>
  );
}
