/**
 * propose:book-coverage — LLM-assisted book-coverage ledger authoring (see
 * docs/superpowers/specs/2026-07-15-book-coverage-ledger-design.md).
 *
 * Two modes, both read-only on the repo (the human reviews and commits):
 *
 *   --emit-toc      Generate the vendored TOC snapshot from the book mirror's
 *                   `index.json`; writes `<lang>.book-toc.proposed.ts`.
 *   --chapter <n>   Propose one coverage decision per section of chapter n,
 *                   grounded in the chapter markdown + the language's
 *                   curriculum; prints a paste-ready ledger fragment (gaps as
 *                   `// GAP` comments) and writes the raw proposals JSON.
 *
 * Usage:
 *   pnpm --filter @language-drill/ai propose:book-coverage \
 *     --book-dir /path/to/spanish-grammar-md --language es --emit-toc
 *   pnpm --filter @language-drill/ai propose:book-coverage \
 *     --book-dir /path/to/spanish-grammar-md --language es --chapter 29
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";

import { ALL_CURRICULA, requireEnv, type TocEntry } from "@language-drill/db";

import {
  proposeBookCoverage,
  renderBookCoverageFragment,
} from "../src/book-coverage-proposal.js";
import { createClaudeClient } from "../src/index.js";

type IndexSection = { number?: string; title: string; anchor: string; level: number };
type IndexFile = {
  file: string;
  kind?: string;
  title: string;
  chapter?: number;
  anchor: string;
  sections?: IndexSection[];
};
type BookIndex = { title?: string; files: IndexFile[] };

const LANGUAGES = {
  es: { code: "ES", name: "Spanish" },
  de: { code: "DE", name: "German" },
  tr: { code: "TR", name: "Turkish" },
} as const;

function loadBookIndex(bookDir: string): BookIndex {
  return JSON.parse(readFileSync(join(bookDir, "index.json"), "utf8")) as BookIndex;
}

/**
 * Flatten the mirror index into TocEntry[]. Parents are resolved by walking
 * the section list in order and tracking the last-seen anchor per level —
 * robust against anchor spellings (chapter anchors are `chNN`, sections `NN-M`).
 */
function buildToc(index: BookIndex): TocEntry[] {
  const toc: TocEntry[] = [];
  for (const file of index.files) {
    toc.push({ anchor: file.anchor, title: file.title, level: 1, parent: null });
    const lastAtLevel = new Map<number, string>([[1, file.anchor]]);
    for (const section of file.sections ?? []) {
      const parent = lastAtLevel.get(section.level - 1) ?? file.anchor;
      toc.push({
        anchor: section.anchor,
        title: section.title,
        level: section.level,
        parent,
      });
      lastAtLevel.set(section.level, section.anchor);
      for (const level of [...lastAtLevel.keys()]) {
        if (level > section.level) lastAtLevel.delete(level);
      }
    }
  }
  return toc;
}

function renderTocModule(lang: string, bookDir: string, toc: readonly TocEntry[]): string {
  const rows = toc
    .map(
      (e) =>
        `  { anchor: ${JSON.stringify(e.anchor)}, title: ${JSON.stringify(e.title)}, level: ${e.level}, parent: ${JSON.stringify(e.parent)} },`,
    )
    .join("\n");
  return `// Generated by propose:book-coverage --emit-toc from ${bookDir}/index.json.
// Vendored TOC snapshot (titles only, no book text) — do not hand-edit.
// Paste into packages/db/src/curriculum/book-coverage/${lang}.ts
export const ${lang.toUpperCase()}_BOOK_TOC: readonly TocEntry[] = [
${rows}
];
`;
}

async function main(): Promise<void> {
  const { values } = parseArgs({
    options: {
      "book-dir": { type: "string" },
      language: { type: "string" },
      chapter: { type: "string" },
      "emit-toc": { type: "boolean", default: false },
      help: { type: "boolean", default: false },
    },
    allowPositionals: false,
  });

  const lang = values.language as keyof typeof LANGUAGES | undefined;
  if (
    values.help ||
    !values["book-dir"] ||
    !lang ||
    !(lang in LANGUAGES) ||
    (!values["emit-toc"] && !values.chapter)
  ) {
    console.log(
      "Usage: propose:book-coverage --book-dir <path> --language es|de|tr (--emit-toc | --chapter <n>)",
    );
    process.exit(values.help ? 0 : 1);
  }

  const bookDir = values["book-dir"];
  const index = loadBookIndex(bookDir);
  const toc = buildToc(index);

  if (values["emit-toc"]) {
    const outPath = `${lang}.book-toc.proposed.ts`;
    writeFileSync(outPath, renderTocModule(lang, bookDir, toc), "utf8");
    console.log(
      `[propose-book-coverage] wrote ${toc.length} TOC entries (${index.files.length} chapters) to ${outPath}`,
    );
    return;
  }

  const chapterNumber = Number(values.chapter);
  const file = index.files.find((f) => f.chapter === chapterNumber);
  if (!file) {
    console.error(`[propose-book-coverage] no chapter ${values.chapter} in ${bookDir}/index.json`);
    process.exit(1);
  }

  const { code, name } = LANGUAGES[lang];
  const curriculum = ALL_CURRICULA.filter(
    (p) => p.language === code && p.kind === "grammar",
  );
  if (curriculum.length === 0) {
    console.error(`[propose-book-coverage] no ${code} grammar points in the curriculum`);
    process.exit(1);
  }

  // Dedupe by anchor — some front-matter files repeat the chapter anchor as a
  // section anchor (seen in the Hammer mirror), which would make the model
  // (correctly) decide the same anchor twice and trip the parser's duplicate
  // guard.
  const seenAnchors = new Set<string>();
  const sections = [
    { anchor: file.anchor, title: file.title },
    ...(file.sections ?? []).map((s) => ({ anchor: s.anchor, title: s.title })),
  ].filter((s) => (seenAnchors.has(s.anchor) ? false : (seenAnchors.add(s.anchor), true)));

  const client = createClaudeClient(requireEnv("ANTHROPIC_API_KEY"));
  const proposals = await proposeBookCoverage(client, {
    book: index.title ?? bookDir,
    languageName: name,
    sections,
    chapterMarkdown: readFileSync(join(bookDir, file.file), "utf8"),
    curriculumSummary: curriculum
      .map((p) => `${p.key} — ${p.name} (${p.cefrLevel}): ${p.description}`)
      .join("\n"),
    curriculumKeys: curriculum.map((p) => p.key),
  });

  const outPath = `${lang}-ch${chapterNumber}.book-coverage.proposed.json`;
  writeFileSync(outPath, JSON.stringify(proposals, null, 2), "utf8");
  const gaps = proposals.filter((p) => "gap" in p).length;
  console.log(
    `\n# Proposed coverage for ${file.title} — review, edit, paste into the ${lang} ledger:\n`,
  );
  console.log(renderBookCoverageFragment(proposals));
  console.log(
    `\n# ${proposals.length} decisions (${gaps} GAP${gaps === 1 ? "" : "s"} to triage); raw proposals written to ${outPath}\n`,
  );
}

const isMain =
  process.argv[1] !== undefined &&
  fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  main().catch((err) => {
    console.error("[propose-book-coverage] unhandled failure:", err);
    process.exit(1);
  });
}
